<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQj02s7w\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQj02s7w/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerQj02s7w.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerQj02s7w\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerQj02s7w\appProdProjectContainer(array(
    'container.build_hash' => 'Qj02s7w',
    'container.build_id' => '07f4854d',
    'container.build_time' => 1536604252,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerQj02s7w');
