<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY0twwsi\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY0twwsi/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerY0twwsi.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerY0twwsi\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerY0twwsi\appProdProjectContainer(array(
    'container.build_hash' => 'Y0twwsi',
    'container.build_id' => 'd1170db0',
    'container.build_time' => 1536834022,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerY0twwsi');
